--- 
framework: mocha
postMerge: 
  pattern: 
    - "specs/single_test.js"
postRun: 
  command: 
    - "node --version"
preMerge: 
  pattern: 
    - "specs/single_test.js"
preRun: 
  command: 
    - "npm i"
    - "npm install selenium-webdriver"
